version: '3'

services:
  vpn:
    build: .
    container_name: ikev2-vpn-server
    privileged: true
    #volumes:
    #  - ./data/:/etc/ipsec.d/
    env_file:
      - .env
    ports:
      - '500:500/udp'
      - '4500:4500/udp'
